### PR TITLE
Add websocket support

### PR DESCRIPTION
**Pull request by Pana**
1.  Add websocket service support
2. Enable pub sub feature

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8)* status: all files reviewed, 6 unresolved discussions (waiting on @Pana)

___
*[src/main/java/conflux/web3j/Account.java, line 138 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKvr9B7nVdwnjcdFTx:-MHKvr9B7nVdwnjcdFTy:bmpislq) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/Account.java#L138)):*
> ```Java
> 		RawTransaction tx = RawTransaction.transfer(this.nonce, to, value, option.epochHeight);
> 		option.updatePriceAndChainId(tx);
> 		option.updateGasLimit(tx);
> ```

code not rebased?

I remember that this code line already added in the last pull request.
___
*[src/main/java/conflux/web3j/CfxPubSub.java, line 14 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKwJqq-J-JzMOnkL5Q:-MHKwJqq-J-JzMOnkL5R:b2xvpl5) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/CfxPubSub.java#L14)):*
> ```Java
>      * @return a {@link Flowable} instance that emits a notification for every new header
>      */
>     Flowable<NewHeadsNotification> newHeadsNotifications();
> ```

How about to rename to `subscribeXxxx`？
___
*[src/main/java/conflux/web3j/CfxPubSub.java, line 17 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKwWnW1kAsMatKbYt1:-MHKwWnW1kAsMatKbYt2:b-lbakfp) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/CfxPubSub.java#L17)):*
> ```
> aa
> ```

typo
___
*[src/main/java/conflux/web3j/response/RevertLog.java, line 8 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKxAH25sYzex9BwO9F:-MHKxAH25sYzex9BwO9G:bfz22w0) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/response/RevertLog.java#L8)):*
> ```Java
>     private String revertTo;
> 
>     public String getRevertTo() { return revertTo; }
> ```

not sure if json deserialization works fine without setter
___
*[src/main/java/conflux/web3j/response/events/Epoch.java, line 9 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKxPo15VtcI-srg6S9:-MHKxPo15VtcI-srg6SA:bpa1sgs) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/response/events/Epoch.java#L9)):*
> ```Java
>     private List<String> epochHashesOrdered;
> 
>     public String getEpochNumber() {return epochNumber;}
> ```

why not use BigInteger type as return type?
___
*[src/main/java/conflux/web3j/response/events/NewHead.java, line 29 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKxhhg54KeMB_MTXK8:-MHKxhhg54KeMB_MTXK9:b-i1o4v1) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/response/events/NewHead.java#L29)):*
> ```Java
>     }
> 
>     public String getBlame() {
> ```

AFAIK, blame is a number.

Please also check for other getters for return type.

**Comment by Pana** [comment]
Now the code is sync with newest code, and the typo method name has been fixed.
For the newHeads epochNumber now keep same with `BlockHeader`, and without setter the deserialization works fine.
But if epochNumber is BigInteger deserialization will not work 😂

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8)* status: all files reviewed, 2 unresolved discussions (waiting on @Pana)

___
*[src/main/java/conflux/web3j/response/events/NewHead.java, line 52 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHLLLSl9Jrl1USV3RWj:-MHLLLSm8NgA9zDg1eqA:b-x0amfp) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/03a909722e165e4f0363ac3d29825c29f5032d52/src/main/java/conflux/web3j/response/events/NewHead.java#L52)):*
> ```
> String
> ```

BigInteger, also check for other getter methods

**Review by Pana — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[src/main/java/conflux/web3j/Account.java, line 138 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKvr9B7nVdwnjcdFTx:-MHLO9ie97YbuWd5HtUn:b-896fjx) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/Account.java#L138)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

code not rebased?

I remember that this code line already added in the last pull request.
</blockquote></details>

Done
___
*[src/main/java/conflux/web3j/response/events/Epoch.java, line 9 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHKxPo15VtcI-srg6S9:-MHLOJi527kO1tI4ia0c:b2nhksp) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/86974409b58ed046059b6bf8d238b686f36090d4/src/main/java/conflux/web3j/response/events/Epoch.java#L9)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

why not use BigInteger type as return type?
</blockquote></details>

OK
___
*[src/main/java/conflux/web3j/response/events/NewHead.java, line 52 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-MHLLLSl9Jrl1USV3RWj:-MHLOPJyEVLX8QQ8mj3_:b2nhksp) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/03a909722e165e4f0363ac3d29825c29f5032d52/src/main/java/conflux/web3j/response/events/NewHead.java#L52)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> String
> ```

BigInteger, also check for other getter methods
</blockquote></details>

OK

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/8#-:-MHLUSQ22c1RuDPu_1Tm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
