### PR TITLE
Add support for new RPC method for conflux-rust v1.1.4

### PR DESCRIPTION
**Pull request by Pana**
Check CHANGELOG

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27)* status: all files reviewed, 7 unresolved discussions (waiting on @Pana)

___
*[CHANGELOG.md, line 17 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf-F8H4L3lMVqWtRPD:-Mbf-F8H4L3lMVqWtRPE:b8d2aua) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/CHANGELOG.md#L17)):*
> ```
> deploy
> ```

Added method `deployFile`, which supports to deploy contract with truffle compiled json file.
___
*[src/main/java/conflux/web3j/Cfx.java, line 130 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf-VrYCmvQk0xb4ZRT:-Mbf-VrYCmvQk0xb4ZRU:b-o2w3tp) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/Cfx.java#L130)):*
> ```Java
> 	Request<Optional<LocalizedBlockTrace>, LocalizedBlockTrace.Response> traceBlock(String blockHash);
> 
> 	Request<Optional<List<LocalizedTrace>>, LocalizedTrace.Response> traceFilter(TraceFilter filter);
> ```

Some of the APIs above are debug/local RPC, strongly recommend to define an extension interface.

Moreover, java and golang sdk should keep consistent in design.
___
*[src/main/java/conflux/web3j/CfxPubSub.java, line 8 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf-wMkAgjXKZq9MOpv:-Mbf-wMkAgjXKZq9MOpw:bg4ltcs) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/CfxPubSub.java#L8)):*
> ```
> import java.util.Optional;
> ```

Did not see the usage, please pay attention to compilation warnings. We should provide a no compilation errors/warnings SDK to users.
___
*[src/main/java/conflux/web3j/response/AccountPendingInfo.java, line 45 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf0x9yDRsinT8Exhg9:-Mbf0x9yDRsinT8ExhgA:b-ojthm8) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/AccountPendingInfo.java#L45)):*
> ```Java
>     public void setNextPendingTx(String nextPendingTx) {
>         this.nextPendingTx = nextPendingTx;
>     }
> ```

Suggest to override `toString` for debug purpose.
___
*[src/main/java/conflux/web3j/response/Action.java, line 9 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf1dsdBhmZJ52Kdqad:-Mbf1dsdBhmZJ52Kdqae:b-1tzqe) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/Action.java#L9)):*
> ```Java
> 
> // TODO There are five kind actions(call, callResult, create, createResult, internalTraces), how to express them in one class
> public class Action {
> ```

In Java world, a base class may be used for abstraction.
___
*[src/main/java/conflux/web3j/response/LocalizedTrace.java, line 85 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf2-fg-N3vksRQZ2xO:-Mbf1tTCExeDnt3sISS2:bmd3te5) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/LocalizedTrace.java#L85)):*
> ```Java
>         result += "\ntype: " + this.type;
>         result += "\naction: " + this.action;
>         return  result;
> ```

Maybe you could write a util method for general `toString`, e.g. gson.toJson(object)
___
*[src/main/java/conflux/web3j/response/Trace.java, line 6 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf2a5HDQ-ODS4yhDjP:-Mbf2a5HDQ-ODS4yhDjQ:bepyqmr) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/Trace.java#L6)):*
> ```Java
> 
> public class Trace {
> ```

No implementation?

**Review by Pana — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27)* status: 11 of 25 files reviewed, 7 unresolved discussions (waiting on @boqiu)

___
*[CHANGELOG.md, line 17 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf-F8H4L3lMVqWtRPD:-MbjVhkf5fjaGnuUa84Z:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/CHANGELOG.md#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> deploy
> ```

Added method `deployFile`, which supports to deploy contract with truffle compiled json file.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Cfx.java, line 130 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf-VrYCmvQk0xb4ZRT:-MbjVjB62XBYVX2fAHr3:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/Cfx.java#L130)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Some of the APIs above are debug/local RPC, strongly recommend to define an extension interface.

Moreover, java and golang sdk should keep consistent in design.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/CfxPubSub.java, line 8 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf-wMkAgjXKZq9MOpv:-MbjVkEY2ui7VHDNJgnv:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/CfxPubSub.java#L8)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> import java.util.Optional;
> ```

Did not see the usage, please pay attention to compilation warnings. We should provide a no compilation errors/warnings SDK to users.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/response/AccountPendingInfo.java, line 45 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf0x9yDRsinT8Exhg9:-MbjXHud6xsYzcjDcP6Y:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/AccountPendingInfo.java#L45)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to override `toString` for debug purpose.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/response/Action.java, line 9 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf1dsdBhmZJ52Kdqad:-MbjXKrL689H53ipA8Vw:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/Action.java#L9)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

In Java world, a base class may be used for abstraction.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/response/LocalizedTrace.java, line 85 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf2-fg-N3vksRQZ2xO:-MbjWi1o1ejxIRsrbBpV:bwiof6y) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/LocalizedTrace.java#L85)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Maybe you could write a util method for general `toString`, e.g. gson.toJson(object)
</blockquote></details>

Temporary removed because action object cannot directly JSON serialized
___
*[src/main/java/conflux/web3j/response/Trace.java, line 6 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbf2a5HDQ-ODS4yhDjP:-MbjVpRlDOMH9I1pv5rR:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/75a07ae63af909cea2d8b425645b2473025602c2/src/main/java/conflux/web3j/response/Trace.java#L6)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

No implementation?
</blockquote></details>

Done.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27)* status: all files reviewed, 5 unresolved discussions (waiting on @Pana)

___
*[src/main/java/conflux/web3j/Debug.java, line 15 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjeTQhBXRRKut7Aumx:-MbjeTQhBXRRKut7Aumy:bknyynb) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/Debug.java#L15)):*
> ```
> getEpochReceipt
> ```

Should be `getEpochReceipts` and the return value type should be `Optional`.
___
*[src/main/java/conflux/web3j/Debug.java, line 19 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbjer42DjOJ4snpr36C:-Mbjer42DjOJ4snpr36D:b-70k3ny) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/Debug.java#L19)):*
> ```Java
>     Request<Optional<AccountPendingInfo>, AccountPendingInfo.Response> getAccountPendingInfo(Address address);
> 
>     Request<AccountPendingTransactions, AccountPendingTransactions.Response> getAccountPendingTransactions(Address address);
> ```

Above 2 APIs are public ones, which defined in cfx.rs file.
___
*[src/main/java/conflux/web3j/Web3j.java, line 30 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjfQP50550MOntGjvA:-MbjfQP50550MOntGjvB:bxtlxp4) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/Web3j.java#L30)):*
> ```
> public
> ```

Strongly recommend not to make this class `public`, Java world usually use interface instead of concrete class.
___
*[src/main/java/conflux/web3j/response/AccountPendingInfo.java, line 52 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjfplB9Ld_XyyANo6N:-MbjfplB9Ld_XyyANo6O:bpxdgop) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/response/AccountPendingInfo.java#L52)):*
> ```Java
>     public String toString() {
>         try {
>             return ToStringUtils.getObjectMapper().writeValueAsString(this);
> ```

Why not provide a method in `ToStringUtils` to convert any object to a json string without exception (or runtime exception instead).
___
*[src/main/java/conflux/web3j/utils/ToStringUtils.java, line 5 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjgaceCF0M_8jzQrLT:-MbjgaceCF0M_8jzQrLU:bf4ynjs) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/utils/ToStringUtils.java#L5)):*
> ```Java
> import com.fasterxml.jackson.databind.ObjectMapper;
> 
> public class ToStringUtils {
> ```

Suggest to create a class `Utils` for various utilities, not only for `toString` purpose.

**Review by Pana — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27)* status: 16 of 26 files reviewed, 5 unresolved discussions (waiting on @boqiu)

___
*[src/main/java/conflux/web3j/Debug.java, line 15 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjeTQhBXRRKut7Aumx:-MbsuKNU-LeU0FY1HJo2:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/Debug.java#L15)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> getEpochReceipt
> ```

Should be `getEpochReceipts` and the return value type should be `Optional`.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Debug.java, line 19 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-Mbjer42DjOJ4snpr36C:-MbsuKmJEzpALnxOKnYp:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/Debug.java#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Above 2 APIs are public ones, which defined in cfx.rs file.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Web3j.java, line 30 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjfQP50550MOntGjvA:-MbsuLjm4kjtl1bQSyWv:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/Web3j.java#L30)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> public
> ```

Strongly recommend not to make this class `public`, Java world usually use interface instead of concrete class.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/response/AccountPendingInfo.java, line 52 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjfplB9Ld_XyyANo6N:-MbsuMUZ5X9rwdyf2ey6:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/response/AccountPendingInfo.java#L52)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not provide a method in `ToStringUtils` to convert any object to a json string without exception (or runtime exception instead).
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/utils/ToStringUtils.java, line 5 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27#-MbjgaceCF0M_8jzQrLT:-MbsuO0V2SVB6mWtxKZn:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/20eaf1d29ab6cf5730d714175eda2b96e32f5afa/src/main/java/conflux/web3j/utils/ToStringUtils.java#L5)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to create a class `Utils` for various utilities, not only for `toString` purpose.
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana)

**Pull request merged**
