### PR TITLE
Internal contracts

### PR DESCRIPTION
**Pull request by Pana**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15)* status: all files reviewed, 9 unresolved discussions (waiting on @Pana)

___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 10 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaCd205fPAZMOcokdg:-MOaCd205fPAZMOcokdh:beg1btu) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L10)):*
> ```Java
> import conflux.web3j.Cfx;
> 
> public class AdminControl extends ContractCall {
> ```

How about to move to sub-package `internal`?
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 11 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOa8a-N2-gSRL7_65pE:-MOa8a-O1RRaJ4oYO7Pz:bigztuj) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L11)):*
> ```Java
> 
> public class AdminControl extends ContractCall {
>     static String contract = "0x0888000000000000000000000000000000000000";
> ```

Why not declare it as `private final static`?
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 27 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOa9IHDANntBFbacOtf:-MOa9IHDANntBFbacOtg:b-fr772s) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L27)):*
> ```
> address
> ```

Suggest to rename to `contract` or `contractAddress`, and also keep consistent with other APIs. Naming convention is very important, otherwise you need to add necessary comment instead.

Moreover, strongly recommend to keep consistent with solidity file.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 29 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOa9TBY1GfPwMDGgXq5:-MOa9TBY1GfPwMDGgXq6:b1tm2e2) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L29)):*
> ```Java
>     public String getAdmin(String address) throws RpcException {
>         String encodedResult = this.call("getAdmin", new Address(address)).sendAndGet();
>         return DecodeUtil.decode(encodedResult, Address.class);
> ```

I remember that you've already added a new method `callAndGet`.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 32 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaA6oPANSwlPAvIFiJ:-MOaA6oPANSwlPAvIFiK:b-63ieem) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L32)):*
> ```Java
>     }
> 
>     public void destroy (Option option, String contractAddress) throws Exception {
> ```

1) Better to return the sent tx hash for all `write` APIs.
2) If possible, why not  remove the 1st parameter `Option` and use default value or hard coded value in the implementation.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 36 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaAVajDRRP0HC8eD-n:-MOaAVajDRRP0HC8eD-o:b-f0ksda) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L36)):*
> ```Java
>     }
> 
>     public void setAdmin(Option option, String contractAddress, String admin) throws Exception {
> ```

How about to check if `this.account` is the contract admin to avoid contract execution failure?

BTW, many `write` APIs requires `admin` privilege.
___
*[src/main/java/conflux/web3j/contract/ERC20.java, line 12 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaC0ToE0fJ6J4tg6wA:-MOaC0ToE0fJ6J4tg6wB:b-qu4lfc) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/ERC20.java#L12)):*
> ```Java
> import java.math.BigInteger;
> 
> public class ERC20 extends ContractCall{
> ```

Solidity allow multiple inheritance, maybe interface with default implementation is better than a concrete class. We can can more discussion and refactor in future.
___
*[src/main/java/conflux/web3j/contract/ERC20.java, line 51 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaBlCL4SjhsFhKNHq9:-MOaBlCMD3F4DEVLjTAv:b-crm7ch) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/ERC20.java#L51)):*
> ```Java
>     public String transferFrom(Account.Option option, String sender, String recipient, BigInteger amount) throws Exception {
>         return this.account.call(option, this.contract, "transferFrom", new Address(sender), new Address(recipient), new Uint256(amount));
>     }
> ```

There're some other APIs in IERC20.sol missed, suggest to supplement those APIs in future.
___
*[src/main/java/conflux/web3j/contract/SponsorWhitelistControl.java, line 66 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaDfbF4IaLTakZ2lkE:-MOaDfbGBtL1vasyrAJ9:b9pg5j1) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/SponsorWhitelistControl.java#L66)):*
> ```Java
>     }
> 
>     public boolean isAllWhitelisted(String address) throws RpcException {
> ```

How about to provide a more user friendly API to return all sponsor info for a given contract?

As for the perf, is it possible to query all sponsor info in a batch rpc call?

BTW, the same to staking contract.

**Review by Pana — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15)* status: 7 of 13 files reviewed, 9 unresolved discussions (waiting on @boqiu)

___
*[src/main/java/conflux/web3j/contract/ERC20.java, line 12 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaC0ToE0fJ6J4tg6wA:-MOe9zuA00dI_0kVtqdi:b-q2c8qf) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/ERC20.java#L12)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Solidity allow multiple inheritance, maybe interface with default implementation is better than a concrete class. We can can more discussion and refactor in future.
</blockquote></details>

OK, we can refactor it in the future
___
*[src/main/java/conflux/web3j/contract/ERC20.java, line 51 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaBlCL4SjhsFhKNHq9:-MOeB0Bn2K3hy_QqS7xH:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/ERC20.java#L51)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

There're some other APIs in IERC20.sol missed, suggest to supplement those APIs in future.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 10 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaCd205fPAZMOcokdg:-MOeAFyR9sxBJR9i8XUw:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L10)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to move to sub-package `internal`?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 11 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOa8a-N2-gSRL7_65pE:-MOeAGbB1TI48vFDiBpu:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L11)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not declare it as `private final static`?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 27 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOa9IHDANntBFbacOtf:-MOeAHYgAa_rxKLizUbU:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> address
> ```

Suggest to rename to `contract` or `contractAddress`, and also keep consistent with other APIs. Naming convention is very important, otherwise you need to add necessary comment instead.

Moreover, strongly recommend to keep consistent with solidity file.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 29 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOa9TBY1GfPwMDGgXq5:-MOeAI2w3Rm4lWjI2XY_:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L29)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I remember that you've already added a new method `callAndGet`.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 32 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaA6oPANSwlPAvIFiJ:-MOeHkzb9g_Zgf4y24s6:b-sn2q41) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L32)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) Better to return the sent tx hash for all `write` APIs.
2) If possible, why not  remove the 1st parameter `Option` and use default value or hard coded value in the implementation.
</blockquote></details>

For the option parameter, i think we can keep it now, maybe someone want pass custom tx parameter, we can discuss a better solution later
___
*[src/main/java/conflux/web3j/contract/AdminControl.java, line 36 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaAVajDRRP0HC8eD-n:-MOeALID7lgtB8eU7InD:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/AdminControl.java#L36)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to check if `this.account` is the contract admin to avoid contract execution failure?

BTW, many `write` APIs requires `admin` privilege.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/SponsorWhitelistControl.java, line 66 at r2](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOaDfbF4IaLTakZ2lkE:-MOeJwMa4R05XCJcAL9e:b-2ligkx) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/d510664c7af09b887f7a4c6ff05dfc1e56faf32d/src/main/java/conflux/web3j/contract/SponsorWhitelistControl.java#L66)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to provide a more user friendly API to return all sponsor info for a given contract?

As for the perf, is it possible to query all sponsor info in a batch rpc call?

BTW, the same to staking contract.
</blockquote></details>

Should we keep methods same as solidity code, and provide all sponsor info in a outside class ? 
We can add these function next version

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15)* status: all files reviewed, 3 unresolved discussions (waiting on @Pana)

___
*[src/main/java/conflux/web3j/contract/internals/AdminControl.java, line 34 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOePv3L31wmfrRjeZKK:-MOePv3L31wmfrRjeZKL:b-y98ze5) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/0d5e5e575dd01f17cc05faacf5ad5fe387f4b2de/src/main/java/conflux/web3j/contract/internals/AdminControl.java#L34)):*
> ```Java
>     public String destroy (Option option, String contractAddr) throws Exception {
>         String admin = getAdmin(contractAddr);
>         if (admin != account.getAddress()) {
> ```

Should use `equalsIgnoreCase` of `String` to check if 2 strings are the same.
___
*[src/main/java/conflux/web3j/contract/internals/AdminControl.java, line 35 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOePl_b9Chw5i9qOTV-:-MOePl_b9Chw5i9qOTV0:bwqwqdg) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/0d5e5e575dd01f17cc05faacf5ad5fe387f4b2de/src/main/java/conflux/web3j/contract/internals/AdminControl.java#L35)):*
> ```
> Not admin
> ```

Administrator privilege required
___
*[src/main/java/conflux/web3j/contract/internals/Staking.java, line 30 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOeQaXrDvh5n53q4XlJ:-MOeQaXs261LnErj6g_h:b-7x4p2l) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/0d5e5e575dd01f17cc05faacf5ad5fe387f4b2de/src/main/java/conflux/web3j/contract/internals/Staking.java#L30)):*
> ```
> blockNumber
> ```

`user`?

**Review by Pana — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @boqiu)

___
*[src/main/java/conflux/web3j/contract/internals/AdminControl.java, line 34 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOePv3L31wmfrRjeZKK:-MOecK1A0NpbPleZBRc4:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/0d5e5e575dd01f17cc05faacf5ad5fe387f4b2de/src/main/java/conflux/web3j/contract/internals/AdminControl.java#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Should use `equalsIgnoreCase` of `String` to check if 2 strings are the same.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/internals/AdminControl.java, line 35 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOePl_b9Chw5i9qOTV-:-MOecKYA0wI558Mf9zGW:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/0d5e5e575dd01f17cc05faacf5ad5fe387f4b2de/src/main/java/conflux/web3j/contract/internals/AdminControl.java#L35)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Not admin
> ```

Administrator privilege required
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/internals/Staking.java, line 30 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-MOeQaXrDvh5n53q4XlJ:-MOecLEv2uGT1MzVsKus:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/0d5e5e575dd01f17cc05faacf5ad5fe387f4b2de/src/main/java/conflux/web3j/contract/internals/Staking.java#L30)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> blockNumber
> ```

`user`?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/15#-:-MOecxP68w0rdYZWsej_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana)

**Pull request merged**
